[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nub"
path = "src/main.rs"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
include_dir = "0.7.4"
inquire = "0.7.5"
thiserror = "2.0.12"
